version: '3'
services:
  internal-finedr:
    build:
      context: ./finedr
    ports:
    - "5000:5000"
    restart: unless-stopped
    container_name: finedr
    image: web-finedr
    depends_on:
      - internal-nginx
    networks: 
      - nginx-net
